# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload_img/')),
                ('water', models.FloatField(default=0.0)),
                ('created_dt_tm', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
