# Generated by Django 2.1 on 2020-02-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_reco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='water',
            new_name='blueprint',
        ),
        migrations.AddField(
            model_name='image',
            name='house',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='image',
            name='others',
            field=models.FloatField(default=0.0),
        ),
    ]
